import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  headerIcon: { color: "var(--accent)" } satisfies CSSProperties,
  headerTitle: {
    margin: 0,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  empty: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  item: { display: "flex", gap: 10, alignItems: "baseline", minWidth: 0 } satisfies CSSProperties,
  bullet: { flexShrink: 0, fontSize: 9, color: "var(--accent)" } satisfies CSSProperties,
  body: { display: "flex", flexWrap: "wrap", alignItems: "baseline", columnGap: 0, rowGap: 2, minWidth: 0, flex: 1 } satisfies CSSProperties,
  ref: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    padding: 0,
    border: "none",
    background: "transparent",
    color: "var(--accent)",
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  reason: {
    fontSize: 13,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  notInDiff: { fontSize: 12, color: "var(--text-muted)", fontStyle: "italic", marginLeft: 8 } satisfies CSSProperties,
} as const;
