import type { CSSProperties } from "react";

/** Co-located styles for ContextDocRow. */
export const s = {
  row: (attached: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: `1px solid ${attached ? "var(--border-strong)" : "var(--border)"}`,
    background: attached ? "var(--bg-elevated)" : "var(--bg-surface)",
    listStyle: "none",
  }),
  dragging: { position: "relative", zIndex: 2, boxShadow: "var(--shadow-modal)" } satisfies CSSProperties,
  handleSlot: { width: 22, display: "inline-flex", justifyContent: "center", flexShrink: 0 } satisfies CSSProperties,
  handle: (disabled: boolean): CSSProperties => ({
    display: "inline-grid",
    placeItems: "center",
    width: 22,
    height: 22,
    border: "none",
    borderRadius: 4,
    background: "transparent",
    color: "var(--text-muted)",
    cursor: disabled ? "not-allowed" : "grab",
    opacity: disabled ? 0.4 : 1,
    touchAction: "none",
  }),
  name: {
    display: "inline-block",
    maxWidth: 280,
    verticalAlign: "bottom",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  folder: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  label: { flexShrink: 0, maxWidth: "60%" } satisfies CSSProperties,
  trail: { display: "inline-flex", alignItems: "center", gap: 10, flexShrink: 0 } satisfies CSSProperties,
} as const;
