import type { CSSProperties } from "react";

export const s = {
  wrap: {
    display: "flex",
    gap: 18,
    alignItems: "flex-start",
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  iconBox: (bg: string, color: string): CSSProperties => ({
    width: 40,
    height: 40,
    borderRadius: 9,
    display: "grid",
    placeItems: "center",
    background: bg,
    color,
    flexShrink: 0,
  }),
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  label: (color: string): CSSProperties => ({ fontSize: 18, fontWeight: 700, color }),
  refresh: { marginLeft: "auto" } satisfies CSSProperties,
  summary: {
    margin: "8px 0 0",
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  scoreCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
  } satisfies CSSProperties,
  scoreLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  costRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    marginTop: 5,
    paddingTop: 6,
    borderTop: "1px solid var(--border)",
    fontSize: 11.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  costIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  costTokens: { color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
