import type { CSSProperties } from "react";

/* Typography/spacing from the design mockup's IntentBlock (screen_pr_detail.jsx). */
export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  } satisfies CSSProperties,
  emptyStack: { display: "flex", flexDirection: "column", gap: 14, minWidth: 0 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  headerIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  headerTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  headerRight: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  hint: {
    margin: 0,
    fontSize: 12,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  text: {
    margin: 0,
    fontSize: 14,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.5,
    textWrap: "pretty",
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 18,
  } satisfies CSSProperties,
  scopeBlock: { minWidth: 0 } satisfies CSSProperties,
  scopeLabel: (inScope: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 5,
    marginBottom: 7,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: inScope ? "var(--ok)" : "var(--text-muted)",
  }),
  scopeList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  } satisfies CSSProperties,
  scopeItem: (inScope: boolean): CSSProperties => ({
    display: "flex",
    gap: 7,
    fontSize: 12.5,
    lineHeight: 1.45,
    color: inScope ? "var(--text-secondary)" : "var(--text-muted)",
  }),
  scopeDot: (inScope: boolean): CSSProperties => ({
    marginTop: 1,
    color: inScope ? "var(--ok)" : "var(--text-muted)",
  }),
  sourcesBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  sourcesLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  sourceList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
  } satisfies CSSProperties,
  sourceIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  sourceRef: {
    color: "var(--accent)",
    textDecoration: "none",
  } satisfies CSSProperties,
  sourceRefPlain: {
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sourceStatus: (ok: boolean): CSSProperties => ({
    color: ok ? "var(--text-secondary)" : "var(--text-muted)",
    fontStyle: ok ? "normal" : "italic",
  }),
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  footerModel: { color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
