import type { CSSProperties } from "react";

export const s = {
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  item: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 12px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    textAlign: "left",
  } satisfies CSSProperties,
  chevron: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  codeIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  symbol: { fontWeight: 600 } satisfies CSSProperties,
  count: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  panel: {
    padding: "4px 12px 12px 36px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  caller: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  callerName: { color: "var(--text-primary)" } satisfies CSSProperties,
  link: { color: "var(--accent)", textDecoration: "none" } satisfies CSSProperties,
  plain: { color: "var(--text-secondary)" } satisfies CSSProperties,
  chips: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  } satisfies CSSProperties,
} as const;
