import type { CSSProperties } from "react";

/* Spacing and tree-guide geometry from the design mockup's BlastRadiusTree / TreeRow. */
const CHIPS: CSSProperties = {
  listStyle: "none",
  margin: 0,
  display: "flex",
  flexWrap: "wrap",
  gap: 6,
};

export const s = {
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  row: (open: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    padding: "5px 6px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    background: open ? "var(--bg-hover)" : "transparent",
    color: "var(--text-primary)",
    fontFamily: "inherit",
    textAlign: "left",
  }),
  more: {
    marginTop: 6,
    padding: "4px 6px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    flexShrink: 0,
    transform: open ? "rotate(90deg)" : "none",
    transition: "transform .12s",
  }),
  codeIcon: { color: "var(--accent)", flexShrink: 0 } satisfies CSSProperties,
  symbol: { fontSize: 12.5, fontWeight: 600 } satisfies CSSProperties,
  count: {
    marginLeft: "auto",
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  panel: { padding: "4px 0 8px 14px" } satisfies CSSProperties,
  callers: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  caller: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "3px 0 3px 18px",
    fontSize: 12.5,
  } satisfies CSSProperties,
  guideV: (last: boolean): CSSProperties => ({
    position: "absolute",
    left: 8,
    top: 0,
    bottom: last ? "50%" : 0,
    width: 1,
    background: "var(--border-strong)",
  }),
  guideH: {
    position: "absolute",
    left: 8,
    top: "50%",
    width: 8,
    height: 1,
    background: "var(--border-strong)",
  } satisfies CSSProperties,
  callerIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  link: {
    fontSize: 12,
    color: "var(--text-secondary)",
    textDecoration: "none",
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  plain: { fontSize: 12, color: "var(--text-secondary)", minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  endpoints: { ...CHIPS, padding: "8px 0 2px 18px" } satisfies CSSProperties,
  crons: { ...CHIPS, padding: "6px 0 2px 18px" } satisfies CSSProperties,
} as const;
