import type { CSSProperties } from "react";

export const s = {
  section: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 } satisfies CSSProperties,
  heading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  empty: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  row: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: 0,
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
    minWidth: 0,
  } satisfies CSSProperties,
  icon: (color: string): CSSProperties => ({ color, flexShrink: 0 }),
  title: { flex: 1, minWidth: 0, fontSize: 13.5, fontWeight: 600, overflowWrap: "anywhere" } satisfies CSSProperties,
  severity: (color: string): CSSProperties => ({ fontSize: 11, fontWeight: 600, color, flexShrink: 0 }),
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    flexShrink: 0,
    transform: open ? "rotate(180deg)" : undefined,
  }),
  refs: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 6, paddingLeft: 24, minWidth: 0 } satisfies CSSProperties,
  ref: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    padding: "1px 6px",
    border: "1px solid var(--border)",
    borderRadius: 5,
    background: "var(--bg-surface)",
    color: "var(--accent)",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  refPlain: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  notInDiff: { fontSize: 12, color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
  explanation: {
    margin: 0,
    paddingLeft: 24,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
} as const;
