import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minWidth: 0,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  headerIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  headerTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  summary: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  stats: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "4px 10px",
  } satisfies CSSProperties,
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  statIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  statValue: { fontWeight: 650, color: "var(--text-primary)" } satisfies CSSProperties,
  segmented: {
    marginLeft: "auto",
    flexShrink: 0,
    display: "flex",
    gap: 2,
    padding: 2,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
  } satisfies CSSProperties,
  segment: (active: boolean): CSSProperties => ({
    padding: "3px 8px",
    fontSize: 11.5,
    fontWeight: 600,
    fontFamily: "inherit",
    borderRadius: 5,
    border: "none",
    cursor: "pointer",
    background: active ? "var(--bg-elevated)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
  }),
  degraded: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 13,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  degradedText: { flex: 1, minWidth: 200 } satisfies CSSProperties,
  muted: {
    margin: 0,
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
