import type { CSSProperties } from "react";

/* Chip look from the PR Brief mockup: compact bordered chip, bold title over a mono accent ref,
   a separate bordered chevron button attached on the right. */
export const s = {
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    minWidth: 0,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  headerIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  headerTitle: {
    margin: 0,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  empty: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 6,
    minWidth: 0,
  } satisfies CSSProperties,
  item: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
    maxWidth: "100%",
    minWidth: 0,
  } satisfies CSSProperties,
  chip: {
    display: "flex",
    alignItems: "stretch",
    gap: 6,
    maxWidth: "100%",
    minWidth: 0,
  } satisfies CSSProperties,
  main: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: "6px 10px",
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-surface)",
    minWidth: 0,
  } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 6, minWidth: 0 } satisfies CSSProperties,
  icon: (color: string): CSSProperties => ({ color, display: "inline-flex", flexShrink: 0 }),
  title: { fontSize: 12.5, fontWeight: 700, color: "var(--text-primary)", overflowWrap: "anywhere" } satisfies CSSProperties,
  ref: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    padding: 0,
    border: "none",
    background: "transparent",
    color: "var(--accent)",
    fontSize: 11.5,
    cursor: "pointer",
  } satisfies CSSProperties,
  refPlain: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 11.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  toggle: {
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    width: 28,
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-surface)",
    cursor: "pointer",
    padding: 0,
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : undefined,
  }),
  notInDiff: { fontSize: 12, color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
  explanation: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
} as const;
