import type { CSSProperties } from "react";

export const s = {
  wrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    width: "fit-content",
    cursor: "help",
  } satisfies CSSProperties,
  count: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11.5,
    fontWeight: 600,
    color,
    borderBottom: `1px dotted ${color}`,
    paddingBottom: 1,
  }),
  /* Positioned shell: the 8px offset is transparent padding, not margin, so the
     pointer stays inside the hover target while crossing from the counters to the
     box — a margin gap fired mouseleave and closed the popover. */
  pop: (up: boolean, width: number): CSSProperties => ({
    position: "absolute",
    left: 0,
    ...(up ? { bottom: "100%", paddingBottom: 8 } : { top: "100%", paddingTop: 8 }),
    zIndex: 30,
    width,
    cursor: "default",
    textAlign: "left",
  }),
  box: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 10,
    boxShadow: "var(--shadow-modal)",
    padding: 12,
  } satisfies CSSProperties,
  popTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    marginBottom: 9,
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 9,
    maxHeight: 300,
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "contain",
  } satisfies CSSProperties,
  item: (last: boolean): CSSProperties => ({
    paddingBottom: last ? 0 : 9,
    borderBottom: last ? "none" : "1px solid var(--border)",
  }),
  itemHead: { display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" } satisfies CSSProperties,
  itemTitle: { fontSize: 12.5, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  category: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  itemMeta: { display: "flex", alignItems: "center", gap: 10, marginTop: 5 } satisfies CSSProperties,
  /* Long unbroken paths must wrap, or they widen the list and add a horizontal scrollbar. */
  lineRef: { fontSize: 11, color: "var(--accent-text)", minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  lineLink: {
    fontSize: 11,
    color: "var(--accent-text)",
    minWidth: 0,
    overflowWrap: "anywhere",
    textDecoration: "underline",
    textDecorationStyle: "dotted",
    textUnderlineOffset: 2,
  } satisfies CSSProperties,
  confidence: { flexShrink: 0 } satisfies CSSProperties,
  rationale: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
    marginTop: 5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  status: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
