import type { CSSProperties } from "react";

export const s = {
  section: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 } satisfies CSSProperties,
  headingRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  heading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  empty: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  item: { display: "flex", gap: 10, alignItems: "flex-start", minWidth: 0 } satisfies CSSProperties,
  number: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 700,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  body: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0, flex: 1 } satisfies CSSProperties,
  ref: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    padding: 0,
    border: "none",
    background: "transparent",
    color: "var(--accent)",
    fontSize: 12.5,
    cursor: "pointer",
  } satisfies CSSProperties,
  reason: {
    fontSize: 13,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  notInDiff: { fontSize: 12, color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
} as const;
