import type { CSSProperties } from "react";

/* Spacing, timeline and typography from the design mockup's HistoryAccordion / HistoryRow. */
export const s = {
  root: {
    borderTop: "1px solid var(--border)",
    paddingTop: 16,
    marginTop: 4,
  } satisfies CSSProperties,
  accordion: {
    border: "1px solid var(--border)",
    borderRadius: 7,
    overflow: "hidden",
  } satisfies CSSProperties,
  toggle: (open: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "9px 12px",
    border: "none",
    cursor: "pointer",
    background: open ? "var(--bg-surface)" : "transparent",
    color: "var(--text-primary)",
    fontFamily: "inherit",
    textAlign: "left",
  }),
  icon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  title: { fontSize: 12.5, fontWeight: 600 } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    marginLeft: "auto",
    color: "var(--text-muted)",
    flexShrink: 0,
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .15s",
  }),
  list: {
    listStyle: "none",
    margin: 0,
    padding: "4px 0",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  row: (last: boolean): CSSProperties => ({
    display: "flex",
    gap: 12,
    padding: "10px 14px",
    borderBottom: last ? "none" : "1px solid var(--border)",
  }),
  rail: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 3,
  } satisfies CSSProperties,
  dot: {
    width: 8,
    height: 8,
    borderRadius: 99,
    background: "var(--text-muted)",
    border: "2px solid var(--bg-elevated)",
    boxSizing: "content-box",
  } satisfies CSSProperties,
  line: { width: 1, flex: 1, background: "var(--border)", marginTop: 2 } satisfies CSSProperties,
  body: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  titleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  number: { fontSize: 12, color: "var(--accent-text)" } satisfies CSSProperties,
  link: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)", textDecoration: "none" } satisfies CSSProperties,
  prTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  meta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "4px 0 6px",
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  avatar: { display: "inline-flex" } satisfies CSSProperties,
  notes: {
    margin: 0,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
} as const;
